/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_npe4_RelationshipTest
{
    private static testmethod void testTrigger()
    {
        // Code to cover the one line trigger, the method called has been tested separately by the packaged tests.
        try { insert new npe4__Relationship__c(); } catch(Exception e) { }
    }
}